### ISSUE TITLE
error when binding multiple sockets ("an argument cannot be used with one or more of the other specified arguments")

### ISSUE THREAD

**Issue by v21** [mitsuhiko/systemfd#29]
Hiya,

Since 0.4.3, it seems like passing in multiple -s arguments is not supported:
`systemfd --no-pid -s http::0.0.0.0:8000 -s http::0.0.0.0:8001 -- cargo watch -x run`
gives me
`error: an argument cannot be used with one or more of the other specified arguments`

Downgrading to 0.4.1 seems to resolve the issue.

**Comment by mitsuhiko** [comment]
Sorry for that. This broke with a clap upgrade. Fixed now.
