### ISSUE TITLE
"Address already in use" when restarting

### ISSUE THREAD

**Issue by joprice** [mitsuhiko/systemfd#6]
After the first run, I see the error:

`error: EADDRINUSE: Address already in use`

Seems like the process isn't releasing the port on shutdown? Is this something I'm doing wrong? I'm using the command:

`systemfd --no-pid -s http::8082 -- cargo watch -x run`

**Comment by ricochet1k** [comment]
This can be fixed by patching systemfd to set SO_REUSEADDR and SO_REUSEPORT.

**Comment by joprice** [comment]
That makes sense.

As a sidenote, after leaving that comment and debugging further, I realized that I had configured https://github.com/mozilla/sccache. I tried disabling it, and find that I now only get into this situation when my process panics.

**Comment by arkN7** [comment]
Same thing here..

**Comment by rattrayalex** [comment]
Is there a workaround to this that doesn't involve patching the crate?

**Comment by mitsuhiko** [comment]
This has been changed for a while, since the latest release also on windows. Reusing can be disabled by passing `--no-reuse`.
