### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by ricochet1k** [mitsuhiko/systemfd#7]
People who work for software companies are often only allowed to contribute to code which has an [explicit Open Source license](https://opensource.google.com/docs/patching/#patches-that-dont-require-any-review). Please add a LICENSE file to your repository. May I suggest MIT or Apache 2?

**Comment by l-2-j** [comment]
Cargo.toml seems to have the license defined as `MIT/Apache-2.0`. It'd still be a good idea to also add those licenses as files though.
