### ISSUE TITLE
[Feature Request] support custom address argument

### ISSUE THREAD

**Issue by chengcyber** [mitsuhiko/systemfd#8]
# Question

I checked the code-base, and see the address is hard code to 127.0.0.1, I would like to pass a 0.0.0.0 as a host.

# Expect

sth like this: `systemfd -s http::0.0.0.0::3000`

**Comment by whentze** [comment]
This actually works already, the hardcoded 127.0.0.1 is just for when you don't give an address.

The syntax looks like this:

`systemfd -s http::0.0.0.0:3000`
